### ISSUE TITLE
Mutation on _meiosis

### ISSUE THREAD

**Issue by oddoking** [kora-labs/chromax#11]
When you create Haploid from _meiosis, are you considering mutation at the moment? or just recombination rate?

**Comment by younik** [comment]
For the moment, just recombination is considered. 
I am happy to accept a contribution for mutation or add it by myself in a couple of weeks.

**Comment by oddoking** [comment]
we will do it sometime next week or so

**Comment by younik** [comment]
Done here https://github.com/kora-labs/chromax/pull/13
