### ISSUE TITLE
Marker effect mean value is calculated wrong?

### ISSUE THREAD

**Issue by oddoking** [kora-labs/chromax#6]
In the TraitModel, the marker effect mean is summing all the marker effects along the n (pop size) dimension. I think it should use the mean function, not the sum function. I verified using  our data whose mean is zero, but Chromax is summing the value. Also after taking the mean, the marker effect values should be subtracted by the mean so that when calculating GEBV, your code will be correct by adding back the mean.

![屏幕截图 2023-12-22 145502](https://github.com/kora-labs/chromax/assets/151606745/5aac5d25-e28b-4a0c-80be-b5d76b10ada7)

**Comment by younik** [comment]
Thanks for helping us improve ChromaX!

That mean refers to the mean value of GEBV assuming the population is drawn from a uniform distribution on all possible individuals; i.e. every marker has an equal probability of having a value 0 or 1.  The first axis in marker_effects is the marker axis; the second will be the number of traits.

If you want to compute the mean of your current population, you should do something like this:
```python
gebvs = simulator.GEBV(population)
gebvs.mean(axis=0)
```

Moreover, these values are only for the diploid population (see https://github.com/kora-labs/chromax/issues/1), I hope to have time to design it better soon.

So with the previous assumptions, the mean of a random population will be the sum of the marker_effects as the summed markers values on the diploidy axis will have values 2 with 25% probability, 1 with 50% probability, and 0 with 25% probability.

Does this make sense? Sorry for the confusion, I should make it clearer and maybe even private those values (I needed them for some of my experiments, but they are not very interesting for the user maybe).

**Comment by oddoking** [comment]
[GEBV.xlsx](https://github.com/kora-labs/chromax/files/13757444/GEBV.xlsx)
![image](https://github.com/kora-labs/chromax/assets/151606745/145be575-c9d6-44cb-8d62-40f3c61d447d)

Thanks for your reply. I think it deserves a follow-up chat. I attached an example of how to calcuate GEBV for one individual. The chromax mean is the sum of marker effects (1.4), When I calculate the GEBV, it is the dot product of monoploidy and marker effect. In chromax, the value will be added by the 'mean' (1.4). So I get differernt results.

Do you have an underlying assumption (uniform distribution) so your calculation is correct? also the _effect_properties is called twice when I load a population outputing two means. Where it is called beside my own call?
![image](https://github.com/kora-labs/chromax/assets/151606745/08421ada-e40c-4804-9053-e78afe2b00c2)

**Comment by younik** [comment]
Oh, I see it now, and it is a bug indeed, thanks a lot @oddoking 

There are two different means defined in that class. One is a user-specified one, that should correctly be added to the dot product. The other is what I explained in my previous message and shouldn't be added; it is just something theoretical that I used for GEBV normalization. 

Can you check if https://github.com/kora-labs/chromax/pull/7 looks good for you? Thank you!

A random TraitModel is also generated to simulate GxE effects to simulate phenotyping. If you don't use the phenotype function, you can ignore it

**Comment by oddoking** [comment]
@younik Thanks for responding. I am glad we are contributing. I had a look at your fix. I feel it is not complete. I will create a pull request later to show my thoughts. That would be the easy way for our discussion. Happy New Year~

**Comment by younik** [comment]
Fixed by https://github.com/kora-labs/chromax/pull/7
