### ISSUE TITLE
Error Encountered While Running Example from Documentation

### ISSUE THREAD

**Issue by duanmuwx** [kora-labs/chromax#9]
Hello,

I encountered an error while trying to run an example from the Chromax documentation (https://chromax.readthedocs.io/en/latest/tutorials/wheat_bp.html) using the Chromax package installed via pip.
**Error Description:**
I received the following error message when I attempted to run the code:
![图片.png](https://s2.loli.net/2024/01/02/BCKPRQHbhTFMUED.png)
**Code Snippet:**
```
from chromax import Simulator
from chromax import index_functions
from chromax.sample_data import genome, genetic_map

if __name__ == "__main__":
    simulator = Simulator(
        genetic_map=genetic_map,
        trait_names=["Yield"],
        h2=[0.4]
    )
    f0 = simulator.load_population(genome)
    f1 = simulator.random_crosses(f0, 100)
    dh_lines = simulator.double_haploid(f1, n_offspring=100)
    headrows = simulator.select(
        dh_lines,
        k=5,
        f_index=index_functions.visual_selection(simulator, seed=7)
    )
```
**Issue Details:**
Upon inspection, I found that the index_function.py file in the installed Chromax module does not contain the visual_selection function. However, this function is present in the index_function.py file in the Chromax's GitHub source code. It appears that the published Chromax Python module is not consistent with the GitHub source.

Could you please look into this discrepancy and provide guidance on how to resolve the issue?

Thank you for your assistance.

**Comment by younik** [comment]
Hello @duanmuwx,
you are right, the code on `pypi` is not updated with `visual_selection`. We will release another version soon (next days) that will solve the issue.

Meanwhile, you can install chromax with `pip git+https://github.com/kora-labs/chromax.git` to have the source version

**Comment by duanmuwx** [comment]
Thanks for the quick response and help!

**Comment by younik** [comment]
I released a new version on `pip`, it should be solved now!

**Comment by duanmuwx** [comment]
Thank you for the quick update! I'll try the new version.
